# https://github.com/shrink/actions-document-publish
# https://github.com/marketplace/actions/publish-markdown-as-pdf

name: Convert Markdown to PDF

# ------------------------------------------------------------------------------

on:
  push:
    paths:
    - '/tutorials/**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ------------------------------------------------------------------------------

env:
  GITHUB_TOKEN: ${{ github.token }}

# ------------------------------------------------------------------------------

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'tutorials/test/*.md'

      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'Test.pdf'
          path: ${{ steps.publish-document.outputs.pdf }}
