# This is a basic workflow to help you get started with Actions

name: Convert PDF to Markdown

# Controls when the workflow will run
on:
  push:
    paths:
    - 'tutorials/**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
        
    - name: Create .pdfs
      uses: scottypate/md-to-pdf@v0.1.1
      env:
        # Use this parameter to determine where the generated .pdf(s) will be stored.
        PDF_DIR: './pdfs'
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        # The token is built in to actions. No config required.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add PDF files.
        PULL_REQUEST_TITLE: Add PDF files.
        PULL_REQUEST_BRANCH: pdf-add
        PULL_REQUEST_BODY: Here are the generated PDF files.
        PULL_REQUEST_REVIEWERS: ramdacxp
