name: Node.JS md-to-pdf

# ------------------------------------------------------------------------------

on:
  push:
    paths:
    - '/tutorials/**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ------------------------------------------------------------------------------

jobs:
  create-pdf-test:
    runs-on: ubuntu-latest
    name: Create PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PDF output dirs
        run: |
          mkdir -p pdf/test
          mkdir -p pdf/chatter
          mkdir -p pdf/robots

      - name: Create Test PDF
        run: |
          npx -y md-to-pdf tutorials/test/README.md
          mv tutorials/test/README.pdf pdf/Test.pdf

      - name: List PDFs
        run: |
          ls -R pdf

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'Test PDFs'
          path: 'pdf'
