# https://github.com/pandoc/pandoc-action-example/blob/master/.github/workflows/long.yml
# https://pandoc.org/MANUAL.html#creating-a-pdf

name: PanDoc PDF Conversion

# ------------------------------------------------------------------------------

on:
  push:
    paths:
    - '/tutorials/**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ------------------------------------------------------------------------------

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files
        run: |
          ls -R

      - name: Create Test PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=pdf/test/Test.pdf
            tutorials/test/README.md

      - name: Create Chatter PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --standalone
            --output=pdf/test/Chatter-Build.pdf
            chatter/build/README.md

      - name: List PDFs
        run: ls -R pdf

      - name: Archive PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tutorial-PDF
          path: |
            pdf/*.pdf
