# https://gist.github.com/riggaroo/d828c5ffecf261d3ccc7bde89817dba5
# https://trstringer.com/github-actions-create-release-upload-artifacts/

name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   versionName:
    #     description: 'Version  (e.g. 1.0)'
    #     required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

    # - name: Print Input Version
    #   run: echo Version = ${{ github.event.inputs.versionName }}

    - name: Set date based environments
      run: |
        echo "VERSION=$(date +'v%Y.%m%d.%H%M%S')" >> $GITHUB_ENV
        echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
        echo "TIME=$(date +'%H:%M:%S')" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v2

    - name: Create PDF output dirs
      run: |
        mkdir -p pdf/test

    - name: Create Test PDF
      run: |
        npx -y md-to-pdf tutorials/test/README.md
        mv tutorials/test/README.pdf pdf/test/Test.pdf

    - name: List PDFs
      run: |
        ls -R pdf/test

    # - name: Upload Test Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: 'Test PDFs'
    #     path: 'pdf/test'

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body: "This is release ${{ env.VERSION }} of the PDF tutorials, created on ${{ env.DATE }} at ${{ env.TIME }}."
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload Test.pdf to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/test/Test.pdf
        asset_name: Test.pdf
        asset_content_type: application/pdf
