# https://gist.github.com/riggaroo/d828c5ffecf261d3ccc7bde89817dba5
# https://trstringer.com/github-actions-create-release-upload-artifacts/

name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   versionName:
    #     description: 'Version  (e.g. 1.0)'
    #     required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

    # - name: Print Input Version
    #   run: echo Version = ${{ github.event.inputs.versionName }}

    - name: Set date based environments
      run: |
        echo "VERSION=$(date +'v%Y.%m%d.%H%M%S')" >> $GITHUB_ENV
        echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
        echo "TIME=$(date +'%H:%M:%S')" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v2

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body: "This is release ${{ env.VERSION }} of the PDF tutorials, created on ${{ env.DATE }} at ${{ env.TIME }}."
      env:
        GITHUB_TOKEN: ${{ github.token }}