# https://gist.github.com/riggaroo/d828c5ffecf261d3ccc7bde89817dba5
# https://trstringer.com/github-actions-create-release-upload-artifacts/

name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   versionName:
    #     description: 'Version  (e.g. 1.0)'
    #     required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

    # - name: Print Input Version
    #   run: echo Version = ${{ github.event.inputs.versionName }}

    - name: Set date based environments
      run: |
        echo "VERSION=$(date +'v%Y.%m%d.%H%M%S')" >> $GITHUB_ENV
        echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
        echo "TIME=$(date +'%H:%M:%S')" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate PDFs
      run: |
        mkdir -p pdf
        npx -y md-to-pdf tutorials/test/README.md              && mv tutorials/test/README.pdf              pdf/Test.pdf
        npx -y md-to-pdf tutorials/robots/bee/README.md        && mv tutorials/robots/bee/README.pdf        pdf/WackyRobot-Bee.pdf
        npx -y md-to-pdf tutorials/robots/bob/README.md        && mv tutorials/robots/bob/README.pdf        pdf/WackyRobot-Bob.pdf
        npx -y md-to-pdf tutorials/robots/capacitron/README.md && mv tutorials/robots/capacitron/README.pdf pdf/WackyRobot-Capacitron.pdf
        npx -y md-to-pdf tutorials/robots/marv/README.md       && mv tutorials/robots/marv/README.pdf       pdf/WackyRobot-Marv.pdf
        npx -y md-to-pdf tutorials/robots/resistron/README.md  && mv tutorials/robots/resistron/README.pdf  pdf/WackyRobot-Resistron.pdf
        npx -y md-to-pdf tutorials/chatter/build/README.md     && mv tutorials/chatter/build/README.pdf     pdf/Chatter-Buildguide.pdf
        npx -y md-to-pdf tutorials/chatter/anatomy/README.md   && mv tutorials/chatter/anatomy/README.pdf   pdf/Chatter-Aufbau.pdf
        ls -R pdf

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body: "This is release ${{ env.VERSION }} of the PDF tutorials, created on ${{ env.DATE }} at ${{ env.TIME }}."
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Test.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/Test.pdf
        asset_name: Test.pdf
        asset_content_type: application/pdf

    - name: Upload WackyRobot-Bee.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/WackyRobot-Bee.pdf
        asset_name: WackyRobot-Bee.pdf
        asset_content_type: application/pdf

    - name: Upload WackyRobot-Bob.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/WackyRobot-Bob.pdf
        asset_name: WackyRobot-Bob.pdf
        asset_content_type: application/pdf

    - name: Upload WackyRobot-Capacitron.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/WackyRobot-Capacitron.pdf
        asset_name: WackyRobot-Capacitron.pdf
        asset_content_type: application/pdf

    - name: Upload WackyRobot-Marv.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/WackyRobot-Marv.pdf
        asset_name: WackyRobot-Marv.pdf
        asset_content_type: application/pdf

    - name: Upload WackyRobot-Resistron.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/WackyRobot-Resistron.pdf
        asset_name: WackyRobot-Resistron.pdf
        asset_content_type: application/pdf

    - name: Upload Chatter-Buildguide.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/Chatter-Buildguide.pdf
        asset_name: Chatter-Buildguide.pdf
        asset_content_type: application/pdf

    - name: Upload Chatter-Aufbau.pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/Chatter-Aufbau.pdf
        asset_name: Chatter-Aufbau.pdf
        asset_content_type: application/pdf
