# https://gist.github.com/riggaroo/d828c5ffecf261d3ccc7bde89817dba5
# https://trstringer.com/github-actions-create-release-upload-artifacts/

name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   versionName:
    #     description: 'Version  (e.g. 1.0)'
    #     required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:

    # - name: Print Input Version
    #   run: echo Version = ${{ github.event.inputs.versionName }}

    - name: Create date based tokens
      id: versiontoken
      run: echo "::set-output name=version::$(date +'v%Y.%m%d.%H%M%S')"
        # echo "::set-output name=date::$(date +'%d.%m.%Y')"
        # echo "::set-output name=time::$(date +'%H:%M:%S')"

    - name: Set Time
      run: |
        echo "VERTAG=$(date +'v%Y.%m%d.%H%M%S')" >> $GITHUB_ENV





    - name: Print version
      run: |
        echo "Version = ${{ github.versiontoken.outputs.version }}"
        echo "Env = ${{ env.VERTAG }}"


    - name: Check out code
      uses: actions/checkout@v2

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.versiontoken.outputs.version }}
        tag_name: ${{ github.versiontoken.outputs.version }}
        body_path: "This is release ${{ github.versiontoken.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}